apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqs-access-sa
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID:role/ticketing-sqs-access-role"
