apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-svc-ui
  namespace: ticketing
  labels:
    app: worker-svc-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-svc-ui
  template:
    metadata:
      labels:
        app: worker-svc-ui
    spec:
      enableServiceLinks: false
      priorityClassName: ticketing-priority-worker-ui
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - read-api
                        - write-api
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: worker-svc-ui
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: worker-svc-ui
      serviceAccountName: sqs-access-sa
      containers:
        - name: worker-svc
          image: ticketing/worker-svc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: ticketing-config
            - secretRef:
                name: ticketing-secrets
          env:
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: ticketing-secrets
                  key: SQS_QUEUE_INTERACTIVE_URL
            - name: WORKER_DB_MAX_CONCURRENT
              value: "5"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 15
